checks:
  php:
    code_rating: true
    duplication: true
build:
    php7.2:
      environment:
          php: '7.2'
      nodes:
          analysis:
              project_setup:
                  override: true
              tests:
                  override: [php-scrutinizer-run]
    php7.3:
      environment:
        php: '7.3'
      nodes:
        analysis:
          project_setup:
            override: true
          tests:
            override: [php-scrutinizer-run]

filter:
  paths: [src/*]
  excluded_paths: [vendor/*, tests/*]

tools:
  external_code_coverage: true
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, tests]
