checks:
    php:
        code_rating: true
        duplication: true
build:
    environment:
        php: '7.2.2'

filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*]
before_commands:
    - 'composer update --prefer-source'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]

filter:
    excluded_paths:
        - tests/*

tools:
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    external_code_coverage:
        timeout: 600

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
