checks:
  php:
    code_rating: true
    duplication: true
build:
  nodes:
    php7.4:
      environment:
        php: '7.4'
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
    php8.0:
      environment:
        php: '8.0'
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]

filter:
  paths: [src/*]
  excluded_paths: [vendor/*, tests/*]

tools:
  external_code_coverage: true
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, tests]
